name = "ops-workflow-engine-api"
main = "api/worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "ops-db"
database_id = "eff31bc9-ceb6-4a96-9d82-4b78287882f0"

[[durable_objects.bindings]]
name = "TASK_BOARD"
class_name = "TaskBoardState"
script_name = "ops-workflow-engine-api"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TaskBoardState"]


# Workers Routes (for production)
[route]
pattern = "api.workflow-engine.org/*"
zone_name = "workflow-engine.org"
